version: '3'
services:
 web:
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
    - "./public-html/:/usr/local/apache2/htdocs"
  ports:
   - 80:80
  networks:
   - evan-network
  depends_on:
   - db
 db:
  image: public.ecr.aws/docker/library/mysql:oracle
  environment:
   MYSQL_DATABASE: docker_db
   MYSQL_USER: 1twoBucklemYshOe
   MYSQL_PASSWORD: xT6By=0VzQxYju8es4i00t;ef.dc
   MYSQL_ALLOW_EMPTY_PASSWORD: 0
  networks:
   - evan-network
  volumes:
   - mydata:/var/lib/mysql
 phpmyadmin:
  image: phpmyadmin
  ports:
   - 8000:80
  environment:
   - PMA_HOST=db
   - PMA_PORT=3306
  networks:
  - evan-network
  depends_on:
  - db
networks:
 evan-network:
  driver: bridge

volumes:
 mydata:


